version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip3 install -U black flake8 --user
      - run: black --check .
      - run: flake8 .
  build:
    working_directory: ~/working
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: sudo apt install -y libcgal-dev python-pybind11 cmake mpich libhdf5-dev
      - run: pip install .[test] --user
      - run: pip install pytest pytest-cov pybind11
      - run:
             pip install tox
             tox
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
