version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip3 install -U black flake8 --user
      - run: black --check .
      - run: flake8 .
  build:
    working_directory: ~/working
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: sudo apt install -y cmake
      - run: sudo apt-get install libboost-all-dev
      - run: sudo apt-get install libmpfr-dev
      - run: git clone https://github.com/CGAL/cgal.git && cd cgal/ && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && sudo make install
      - run: sudo apt install -y libhdf5-dev
      - run: sudo apt install -y mpich
      - run: git submodule sync
      - run: git submodule update --init
      - run: pip install . --user
      - run: pip3 install -U pytest pytest-cov --user
      - run:
          command: cd tests && py.test --cov SeismicMesh -m "serial" #&& mpirun -np 2 pytest --cov -m "parallel" .
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
