__version__ = "0.0.1"
__author__ = "Keith Roberts"
__author_email__ = "keithrbt0@gmail.com"
__website__ = "https://github.com/krober10nd/SeismicMesh"
__status__ = "Development Status :: 4 - Beta"
__license__ = "License :: GNU GPL 3.0"
